

import { Inter } from 'next/font/google'
import { Manrope } from 'next/font/google'

import Aos from '@/components/Aos'
import './globals.css'
import Navbar from '../components/navbar/page'
import Footer from '@/components/footer/page'


const inter = Inter({ subsets: ['latin'] })
const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Our Cake',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

 

  return (
    <html lang="en">
      <body className={manrope.className}>
        <Aos/>
        
      <Navbar/>
        {children}
      <Footer/>
        
      </body>
    </html>
  )
}
